name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run `nix build`
        run: nix build .
      - name: "Run tests"
        run: |
          nix develop -c echo OK
          nix develop -c elixir --version
          nix develop -c mix hex.info
